word_list = [
    'iron man',
    'captain america',
    'thor',
    'hulk',
    'black widow',
    'hawkeye',
    'spider-man',
    'doctor strange',
    'black panther',
    'scarlet witch',
    'vision',
    'ant-man',
    'wasp',
    'falcon',
    'winter soldier',
    'star-lord',
    'gamora',
    'drax',
    'rocket',
    'groot',
    'mantis',
    'nebula',
    'loki',
    'captain marvel',
    'shang-chi',
    'america chavez',
    'moon knight',
    'ms. marvel',
    'she-hulk',
    'valkyrie',
    'shuri',
    'yelena ',
    'red guardian',
    'blade',
    'wong',
    'quicksilver',
    'the ancient one',
    'nick fury',
    'maria hill',
    'war machine',
    'peggy carter',
    'heimdall',
    'happy',
    'adam warlock',
    'nova',
    'the watcher',
]
